// Mocks generated by Mockito 5.4.4 from annotations
// in job/test/features/auth/screens/signup_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:either_dart/either.dart' as _i6;
import 'package:get_storage/get_storage.dart' as _i3;
import 'package:job/features/auth/controllers/auth_controller.dart' as _i4;
import 'package:job/features/auth/repos/auth_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepo_0 extends _i1.SmartFake implements _i2.AuthRepo {
  _FakeAuthRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetStorage_1 extends _i1.SmartFake implements _i3.GetStorage {
  _FakeGetStorage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i4.AuthController {
  MockAuthController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepo get authRepo => (super.noSuchMethod(
        Invocation.getter(#authRepo),
        returnValue: _FakeAuthRepo_0(
          this,
          Invocation.getter(#authRepo),
        ),
      ) as _i2.AuthRepo);

  @override
  _i3.GetStorage get getStorage => (super.noSuchMethod(
        Invocation.getter(#getStorage),
        returnValue: _FakeGetStorage_1(
          this,
          Invocation.getter(#getStorage),
        ),
      ) as _i3.GetStorage);

  @override
  bool get isloading => (super.noSuchMethod(
        Invocation.getter(#isloading),
        returnValue: false,
      ) as bool);

  @override
  set isloading(bool? _isloading) => super.noSuchMethod(
        Invocation.setter(
          #isloading,
          _isloading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i6.Either<String, bool>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i6.Either<String, bool>>);

  @override
  _i5.Future<_i6.Either<String, bool>> signup(
    String? name,
    String? email,
    String? password,
    String? number,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [
            name,
            email,
            password,
            number,
          ],
        ),
        returnValue: _i5.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #signup,
            [
              name,
              email,
              password,
              number,
            ],
          ),
        )),
      ) as _i5.Future<_i6.Either<String, bool>>);

  @override
  _i5.Future<_i6.Either<String, bool>> fetchProfile() => (super.noSuchMethod(
        Invocation.method(
          #fetchProfile,
          [],
        ),
        returnValue: _i5.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #fetchProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Either<String, bool>>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
